---
- name: Install Python3, Pip, Figlet, Flask, Psycopg and Requests
  hosts: webservers
   
  tasks:
    - name: Update apt package cache
      become: true
      apt:
        update_cache: yes
    
    - name: Install Python3 and Pip
      become: true
      apt:
        name:
          - python3
          - python3-pip
          - figlet
          - bash
        state: present
    
    - name: Install Flask, psycopg and requests
      become: true
      pip:
        name: 
          - flask==3.0.0
          - psycopg==3.1.16
          - psycopg-binary==3.1.16
          - psycopg-pool
          - requests==2.29.0
        executable: pip3
        state: present
    
    - name: Copy python-script and jinja file to webservers
      copy:
        src: /home/ubuntu/ansible
        dest: /home/ubuntu/
      
    - name: Run mixologyfy
      shell: |
        python3 /home/ubuntu/ansible/mixologyfy.py
      environment:
        APP_TEMPLATE_PATH: /home/ubuntu/ansible/index.html.jinja
      args:
        executable: /bin/bash
    
